name: sss
on: [push]
jobs:
  tests:
    runs-on: ubuntu-24.04
    container: shloang/sss:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          python3 -m pytest